name: side_header_list_view
description: ListView with sticky headers on the side. Inspired by the Android contacts app and the calendar app.
version: 0.0.3
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/side_header_list_view

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: "^1.1.1"


dev_dependencies:
  test: ^0.12.0
